CREATE DATABASE IF NOT EXISTS SoccerMatch;
USE SoccerMatch;

CREATE TABLE Team (
    TeamID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Ranking INT CHECK (Ranking BETWEEN 1 AND 10),
    CreationDate DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SoccerMatch (
    MatchID INT AUTO_INCREMENT PRIMARY KEY,
    Team1ID INT NOT NULL,
    Team2ID INT DEFAULT NULL,
    Score1 INT DEFAULT 0,
    Score2 INT DEFAULT 0,
    FOREIGN KEY (Team1ID) REFERENCES Team(TeamID) ON DELETE CASCADE,
    FOREIGN KEY (Team2ID) REFERENCES Team(TeamID) ON DELETE CASCADE
);


CREATE TABLE TimeSlot (
    TimeSlotID INT AUTO_INCREMENT PRIMARY KEY,
    Date DATE NOT NULL,
    StartTime TIME NOT NULL,
    EndTime TIME NOT NULL,
    IsBooked BOOLEAN DEFAULT FALSE,
    MatchID INT DEFAULT NULL,
    FOREIGN KEY (MatchID) REFERENCES SoccerMatch(MatchID) ON DELETE SET NULL
);


CREATE TABLE Notification (
    NotificationID INT AUTO_INCREMENT PRIMARY KEY,
    SenderID INT NOT NULL,
    ReceiverID INT,
    TimeSlotID INT,
    Message TEXT NOT NULL,
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    NotificationType VARCHAR(50) NOT NULL,
    FOREIGN KEY (SenderID) REFERENCES Team(TeamID) ON DELETE CASCADE,
    FOREIGN KEY (ReceiverID) REFERENCES Team(TeamID) ON DELETE SET NULL,
    FOREIGN KEY (TimeSlotID) REFERENCES TimeSlot(TimeSlotID) ON DELETE SET NULL
);
